donajussara: EQU 10
TESTE2:     EQU NOMENOVO
AGORAVAI: EQU VaIfIlHaO
SECTION TEXT
INPUT donajussara
LOAD donajussara
L1: DIV ADD
STORE  TESTE2
MULT TESTE2
STORE TMP_DATA
LOAD AGORAVAI
SUB TMP_DATA
TESTE2 TMP_DATA
OUTPUT TMP_DATA
COPY NEW_DATA,OLD_DATA
LOAD OLD_DATA
JMPP L1
STOP
SECTION DATA
DOIS: CONST 2
OLD_DATA: SPACE
NEW_DATA: SPACE
TMP_DATA: SPACE
