SECTION TEXT
INPUT OLD_DATA
LOAD OLD_DA[TA
L1 : DIV DO'IS
ST*ORE  NEW_DATA
MULT DOIS;comentario2
STORE TMP_DATA ;comentario 1
LOAD OLD_DATA
SUB TMP_DATA
STORE TMP_DATA
OUTPUT TMP_DATA
COPY NEW_DATA OLD_DATA
;LOAD OLD_DATA
JMPP L*1
STOP

SECTION DATA;
DOIS : CONST 987
OLD_DATA: 0xabcdef
NEW_DA[TA   : -234
TMP_DATA: +398
